In [ ]:
## Here will be the augumentation
# Instead of PIL lib, cv is going to be used here

In [43]:
import os
import cv2

In [44]:
# Input directory: 

base_images_dir = "Images/Resized_Images/images"
base_masks_dir = "Images/Resized_Images/masks"


In [45]:
# Read files - Images and masks

base_images = {}
base_masks = {}

for img_file in os.listdir(base_images_dir):
    if img_file.endswith(".png"):
        # img_num = img_file.split("_")[1] # returns 001.png
        img_num = os.path.splitext(img_file)[0].split("_")[1] # returns 001 -> correct way

        base_images[img_num] = cv2.imread(os.path.join(base_images_dir, img_file))
        mask_file = os.path.join(base_masks_dir, f"label_{img_num}.png")
        mask = cv2.imread(mask_file, cv2.IMREAD_UNCHANGED)

        # Convert mask from 3 channels to 1 channel - needed further for correct augumentation 
        # RGB -> Grayscale conversion
        if mask.ndim == 3:
            mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)
           
        base_masks[img_num] = mask

print(f"{len(base_images)} images and {len(base_masks)} masks have been loaded")

28 images and 28 masks have been loaded


In [46]:
# check if the mask has correct values
print(base_masks['003'])
import numpy as np

unique_values = np.unique(base_masks['003'])
print(unique_values)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[ 0 38]


In [47]:
# Output directory: 

output_images = "Images/Augumented_Images/images"
output_masks = "Images/Augumented_Images/masks"

In [48]:
# Augumentation 01 - Rotating images and masks

import cv2
from albumentations import Compose, Affine
import os

os.makedirs(output_images, exist_ok=True)
os.makedirs(output_masks, exist_ok=True)

# Rotation angles
angles = [10, 30, 60, 90]

for img_num, img in base_images.items():
    mask = base_masks[img_num]

    for angle in angles:
        rot = Compose([Affine(rotate=angle, p=1.0)], p=1.0)
        aug = rot(image=img, mask=mask)
        img_aug = aug['image']
        mask_aug = aug['mask']

        # Save with correct number and nametag
        cv2.imwrite(os.path.join(output_images, f"img_{img_num}_Rotated{angle}Deg.png"), img_aug)
        cv2.imwrite(os.path.join(output_masks, f"label_{img_num}_Rotated{angle}Deg.png"), mask_aug)
        

In [ ]:
# Augumentation 02 - Flipping images and masks

In [ ]:
# Augumentation 03 - Brighthness adjustment for images and masks

In [ ]:
# Augumentation 04 - Brighthness adjustment for images and masks

In [ ]:
# Augumentation 05 - Saturation adjustment for images and masks

In [ ]:
# Augumentation 06 - Contrast adjustment for images and masks

In [ ]:
# Augumentation 07 - Edge detection for images and masks

In [ ]:
# Augumentation 08 - Sharpening adjustment for images and masks

In [ ]:
# Augumentation 09 - Blurring adjustment for images and masks